import {CHAIN_ID,NETWORK_NAME,TX_EXPLORER,IS_LAB} from './network.js';
import {BrowserProvider,Contract,Interface,getAddress,formatEther,formatUnits} from 'ethers';
import {ADDRESSES,TOKEN_ABI,parseAmount,minimumOutput,buildSwap,quoteSwap,verifyContracts} from './settlement.js';
const $=id=>document.getElementById(id);let injected,provider,account,quote,verified=false,busy=false,generation=0;const discovered=new Map();const tokenInterface=new Interface(TOKEN_ABI);
const status=(text,error=false)=>{$('wallet-status').textContent=text;$('wallet-status').classList.toggle('error',error);};
function invalidate(){quote=null;generation++;$('quote-details').hidden=true;$('wallet-execute').disabled=true;$('wallet-approve').disabled=true;}
function accountChanged(){disconnected('Account changed. Reconnect to refresh balances.');}
function chainChanged(){disconnected(`Network changed. Reconnect on ${NETWORK_NAME}.`);}
function disconnected(message='Wallet disconnected.'){injected?.removeListener?.('accountsChanged',accountChanged);injected?.removeListener?.('chainChanged',chainChanged);invalidate();provider?.destroy();provider=null;account=null;verified=false;$('wallet-address').textContent='No wallet connected';$('wallet-allowance').textContent='No allowance loaded';$('wallet-balances').textContent='Connect to read your ETH and USDT balances.';$('wallet-quote').disabled=true;$('wallet-revoke').disabled=true;status(message);}
function errorText(e){if(e.code===4001||e.code==='ACTION_REJECTED')return 'Request declined in your wallet. No new transaction was submitted.';if(e.code==='INSUFFICIENT_FUNDS')return 'Insufficient ETH for the amount and network gas.';if(e.code==='TRANSACTION_REPLACED')return 'Transaction replaced in your wallet. Check wallet history before continuing.';return (e.shortMessage||e.message||'Wallet request failed.').slice(0,250);}
function lock(locked){busy=locked;for(const id of ['wallet-connect','wallet-disconnect','wallet-direction','wallet-amount','slippage','wallet-provider','wallet-quote','wallet-approve','wallet-execute','wallet-revoke'])$(id).disabled=locked;if(!locked){$('wallet-quote').disabled=!account||!verified;$('wallet-revoke').disabled=!account||!verified;$('wallet-execute').disabled=!quote;$('wallet-approve').disabled=!quote||quote.direction!=='buy';}}
async function action(fn){if(busy)return;lock(true);try{await fn();}catch(e){invalidate();status(errorText(e),true);}finally{lock(false);}}
async function identity(){if(!injected||!provider||!account||!verified)throw Error('Connect a wallet first.');const chain=await injected.request({method:'eth_chainId'});const accounts=await injected.request({method:'eth_accounts'});if(Number(chain)!==CHAIN_ID||!accounts.length||getAddress(accounts[0])!==account){disconnected(`Wallet account or network changed. Reconnect on ${NETWORK_NAME}.`);throw Error(`Reconnect on ${NETWORK_NAME}.`);}return account;}
async function balances(){const wallet=await identity();const token=new Contract(ADDRESSES.USDT,TOKEN_ABI,provider);const [eth,usdt,allowance]=await Promise.all([provider.getBalance(wallet,'latest'),token.balanceOf(wallet),token.allowance(wallet,ADDRESSES.ROUTER)]);$('wallet-balances').textContent=`${formatEther(eth)} ETH · ${formatUnits(usdt,6)} USDT`;$('wallet-allowance').textContent=`Current router allowance: ${formatUnits(allowance,6)} USDT`;return {eth,usdt,allowance};}
function addWallet(id,name,p){if(IS_LAB&&id!=='neon-local-testnet')return;if(!p||typeof p.request!=='function'||discovered.has(id))return;discovered.set(id,p);const o=document.createElement('option');o.value=id;o.textContent=name;$('wallet-provider').append(o);if(discovered.size===1)$('wallet-provider').value=id;}
window.addEventListener('eip6963:announceProvider',e=>{const d=e.detail;if(d?.info?.uuid&&d?.info?.name)addWallet(String(d.info.uuid),String(d.info.name),d.provider);});window.dispatchEvent(new Event('eip6963:requestProvider'));if(window.ethereum)addWallet('injected','Browser wallet',window.ethereum);
$('wallet-connect').onclick=()=>action(async()=>{disconnected();injected=discovered.get($('wallet-provider').value);if(!injected)throw Error('No browser wallet found. Open Neon Exchange in a browser with an Ethereum wallet extension, then reload.');await injected.request({method:'eth_requestAccounts'});provider=new BrowserProvider(injected,'any');if(IS_LAB)provider.pollingInterval=250;const accounts=await injected.request({method:'eth_accounts'});account=getAddress(accounts[0]);invalidate();verified=false;await verifyContracts(provider);verified=true;await identity();$('wallet-address').textContent=account;await balances();injected.on?.('accountsChanged',accountChanged);injected.on?.('chainChanged',chainChanged);status(`Connected on ${NETWORK_NAME}. Quotes are read only. Transactions require your wallet signature.`);});
$('wallet-disconnect').onclick=()=>disconnected('Disconnected from this page. Existing token approvals are unchanged.');
for(const id of ['wallet-direction','wallet-amount','slippage'])$(id).oninput=()=>{invalidate();$('wallet-input-label').textContent=$('wallet-direction').value==='sell'?'You pay ETH':'You pay USDT';status('Get a fresh quote to review this trade.');};
$('wallet-provider').onchange=()=>disconnected('Wallet selection changed. Connect the selected wallet.');
$('wallet-quote').onclick=()=>action(async()=>{await identity();invalidate();const marker=generation;const direction=$('wallet-direction').value,amountIn=parseAmount($('wallet-amount').value,direction),slippageBps=Number($('slippage').value);status('Reading Ethereum and comparing direct Uniswap v3 pools…');const q=await quoteSwap(provider,{direction,amountIn});await identity();if(marker!==generation)throw Error('Wallet changed during quote. Try again.');const b=await balances();if(direction==='sell'&&amountIn>=b.eth)throw Error('Keep enough ETH for network gas.');if(direction==='buy'&&amountIn>b.usdt)throw Error('Insufficient USDT balance.');quote={...q,account,slippageBps};const decimals=direction==='sell'?6:18,symbol=direction==='sell'?'USDT':'ETH';$('quote-output').textContent=`${formatUnits(q.amountOut,decimals)} ${symbol}`;$('quote-minimum').textContent=`${formatUnits(minimumOutput(q.amountOut,slippageBps),decimals)} ${symbol}`;$('quote-route').textContent=`Uniswap v3 · ${q.fee/10000}% pool · Impact ${(q.impactBps/100).toFixed(2)}% · Block ${q.block}`;$('quote-recipient').textContent=account;$('quote-details').hidden=false;$('quote-age').textContent='Valid for 30 seconds';status(direction==='buy'&&b.allowance<amountIn?'Review the quote. Approve only the required USDT, then get a fresh quote before swapping.':'Quote ready. Review the recipient, minimum received, and contract before requesting the wallet transaction.');});
async function send(tx,label){await identity();const signer=await provider.getSigner(account);const request={to:tx.to,data:tx.data,value:tx.value??0n,chainId:CHAIN_ID};await provider.call({...request,from:account});const gas=await provider.estimateGas({...request,from:account});const fees=await provider.getFeeData();const available=await provider.getBalance(account,'latest');const limit=gas*120n/100n;const maxFee=fees.maxFeePerGas??fees.gasPrice;if(maxFee===null)throw Error('Unable to estimate network fee.');if(available<(request.value+limit*maxFee))throw Error('Insufficient ETH for this transaction and estimated gas.');await identity();if(tx.quotedAt && Date.now()-tx.quotedAt>30000)throw Error('Quote expired during validation. Get a fresh quote.');status(`${label}: review and confirm in your wallet.`);const sent=await signer.sendTransaction({...request,gasLimit:limit});const row=document.createElement('p'),link=document.createElement('a');link.href=`${TX_EXPLORER}${sent.hash}`;link.target='_blank';link.rel='noreferrer';link.textContent=`${label} · ${account}: ${sent.hash}`;row.append(link);const receiptLabel=document.createElement('span');receiptLabel.textContent=' · Pending';row.append(receiptLabel);$('wallet-history').querySelector('.empty')?.remove();$('wallet-history').prepend(row);invalidate();status('Transaction submitted. Waiting for one confirmation…');try{const receipt=await sent.wait(1,180000);if(!receipt||receipt.status!==1)throw Error('Transaction reverted. Check the transaction receipt for details.');receiptLabel.textContent=' · Confirmed';status(`${label} confirmed in block ${receipt.blockNumber}.`);}catch(e){receiptLabel.textContent=' · Check wallet / receipt';throw e;}if(account)await balances();}
$('wallet-approve').onclick=()=>action(async()=>{await identity();const q=quote;if(!q||q.direction!=='buy')throw Error('Get a buy quote first.');if(Date.now()-q.quotedAt>30000)throw Error('Quote expired. Get a fresh quote before approval.');const {allowance}=await balances();if(allowance>=q.amountIn){status('Your existing allowance is sufficient. No additional approval requested.');return;}if(allowance>0n){await send({to:ADDRESSES.USDT,data:tokenInterface.encodeFunctionData('approve',[ADDRESSES.ROUTER,0n])},'Reset USDT allowance');status('Allowance reset to zero. Get a new quote, then approve the exact amount.');return;}await send({to:ADDRESSES.USDT,data:tokenInterface.encodeFunctionData('approve',[ADDRESSES.ROUTER,q.amountIn])},`Approve ${formatUnits(q.amountIn,6)} USDT`);status('Exact amount approved. Get a fresh quote to review and sign the swap.');});
$('wallet-revoke').onclick=()=>action(async()=>{await identity();const b=await balances();if(b.allowance===0n){status('Router allowance is already zero. No transaction needed.');return;}await send({to:ADDRESSES.USDT,data:tokenInterface.encodeFunctionData('approve',[ADDRESSES.ROUTER,0n])},'Revoke USDT allowance');});
$('wallet-execute').onclick=()=>action(async()=>{await identity();if(!quote)throw Error('Get a quote first.');const q=quote;if(q.account!==account)throw Error('Wallet changed. Get a new quote.');if(q.direction!==$('wallet-direction').value||q.amountIn!==parseAmount($('wallet-amount').value,q.direction)||q.slippageBps!==Number($('slippage').value))throw Error('Trade changed. Get a fresh quote.');const b=await balances();if(q.direction==='buy'&&b.allowance<q.amountIn)throw Error('Approve the required USDT first.');const tx=buildSwap(q);await send({...tx,quotedAt:q.quotedAt},'Swap ETH / USDT');});
setInterval(()=>{if(quote){const left=Math.max(0,30-Math.floor((Date.now()-quote.quotedAt)/1000));$('quote-age').textContent=left?`Valid for ${left} seconds`:'Expired · Get a fresh quote';if(!left){$('wallet-execute').disabled=true;$('wallet-approve').disabled=true;}}},1000);
for(const [id,address] of [['router-address',ADDRESSES.ROUTER],['usdt-address',ADDRESSES.USDT]]){$(id).textContent=address;$(id).href=`https://etherscan.io/address/${address}#code`;}
disconnected('Connect your Ethereum wallet to read balances and request a quote.');


